apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio
  labels:
    app: audio

spec:
  replicas: 1
  selector:
    matchLabels:
      app: audio
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
  template:
    metadata:
      labels:
        app: audio
    spec:
      containers:
        - name: audio
          image: saddagada1/wiki-trivia-audio
          envFrom:
            - configMapRef:
                name: audio-configmap
            - secretRef:
                name: audio-secret
